### ISSUE TITLE
CRC16.h library

### ISSUE THREAD

**Issue by robertkowalewski** [rena2019/ArduinoM24SR#1]
Hello, 
in this library there is used library Crc16.h. Can you say where I can download the same library? I can't find any crc16 library with the same function crcsum() which is used in ArduinoM24SR library.

**Comment by rena2019** [comment]
How to get the Crc16.h + Crc16.cpp is written in "How to use/install" of example code, e.g. https://github.com/rena2019/ArduinoM24SR/blob/master/examples/DisplaySystemFile/DisplaySystemFile.ino 
But after code.google.com is closed you could download the files from 
http://avrdude.sourcearchive.com/documentation/5.4/crc16_8c-source.html and
http://avrdude.sourcearchive.com/documentation/5.4/crc16_8h-source.html
